server:
  port: 31450
spring:
  application:
    name: wk-service-manage-media-processor
  data:
    mongodb:
      uri:  mongodb://root:123@localhost:27017
      database: wk_media
#rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
wk-service-manage-media:
  mq:
    queue-media-video-processor: queue_media_video_processor
    routingkey-media-video: routingkey_media_video
  video-location: E:/bs-wk-code/wk-ui/wk-video/
  ffmpeg-path: D:/JavaTools/ffmpeg/bin/ffmpeg.exe