server:
  port: 31200
spring:
  application:
    name: wk-service-manage-course
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/wk_course?characterEncoding=utf-8
      username: root
      password: 123
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
pagehelper:
  helper‐dialect: mysql

course-publish:
  siteId: 5edc893ba6294b51f0faa9cd
  templateId: 5aec5dd70e661808240ab7a6
  previewUrl: http://www.wk.com/cms/preview/
  pageWebPath: /course/detail/
  pagePhysicalPath: /course/detail/
  dataUrlPre: http://localhost:31200/course/courseview/