server:
  port: 31001
spring:
  application:
    name: wk-service-manage-cms
  data:
    mongodb:
      uri: mongodb://root:123@localhost:27017
      database: wk_cms
  freemarker:
    cache: false
    settings:
      template_update_delay: 0